# Data Containers

tmpdata:
  image: busybox:latest
  volumes:
    - /tmp
    - ~/.cos:/home/.cos


# Service Containers

rabbitmq:
  image: rabbitmq:latest


# Server Containers

web:
  image: dataconservancy/osf:wb-latest
  command: 'invoke server'
  environment:
    - WATERBUTLER_CONFIG=/home/.cos/waterbutler-test.json
#    - SOURCE_BRANCH=develop
    - SOURCE_REPO=https://github.com/emetsger/waterbutler
  ports:
    - 7777:7777
  expose:
    - 7777
  links:
    - rabbitmq:rabbitmq
  volumes_from:
    - tmpdata

celery:
  image: dataconservancy/osf:wb-latest
  command: 'invoke celery'
  environment:
    - SOURCE_BRANCH=develop
    - SOURCE_REPO=https://github.com/emetsger/waterbutler
  links:
    - rabbitmq:rabbitmq
  volumes_from:
    - tmpdata
